version: '3.4'

services:
  online_hairdresser.api:
    image: ${DOCKER_REGISTRY-}onlinehairdresserapi
    ports:
      - 5006:5006
    restart: always
    build:
      context: .
      dockerfile: Online_Hairdresser.API/Dockerfile
    environment:
        ASPNETCORE_APPREQUIREHOST: "*:5006"
        ASPNETCORE_URLS: "http://*:5006"
        TZ: Turkey
        ConnectionStrings__SqlConnection: 
            Host=postgres;Database=postgres;Username=postgres;Password=postgres
    depends_on:
        - postgres
        - pgadmin
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      TZ: Turkey
      POSTGRESQL_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    tty: true
    restart: always
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      TZ: Turkey
      PGADMIN_DEFAULT_EMAIL: hairdresser@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: hairdresser@123
      PGADMIN_LISTEN_PORT: 5050
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:5050"
    tty: true
    depends_on:
      - postgres
    links:
      - postgres  
  frontend:
    container_name: frontend
    image: fthmndrli/online-hairdresser-ui-admin
    ports:
      - "8085:80"
    restart: always
    environment:
       VUE_APP_API_URL: http://localhost:98765/api
    depends_on:
      - online_hairdresser.api
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    ports:
      - 9200:9200
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200

volumes:
    postgres:
    pgadmin: